name: $name$
recipe: drupal9
config:
  composer_version: "2"
  via: apache:2.4
  webroot: $webroot$
  drush: "^10"
  xdebug: true
proxy:
  appserver:
    - $domain$.lndo.site
  mailhog:
    - $domain$-mailhog.lndo.site
services:
  appserver:
    type: php:8.1
    config:
      php: lando/php.ini
    overrides:
      environment:
        DRUSH_OPTIONS_URI: "https://$domain$.drush.lndo.site"
        PHP_IDE_CONFIG: "serverName=appserver"
        LANDO_HOST_IP: "host.docker.internal"
        XDEBUG_CONFIG: "remote_enable=1 remote_host=host.docker.internal"
  database:
    type: mysql:5.7
    creds:
      user: $name$
      password: $name$
      database: $name$
    # port forward custom to connect DB by heidiSQL,...
    # portforward: 1200
  mailhog:
    type: mailhog
    hogfrom:
      - appserver
tooling:
  blt:
    service: appserver
    cmd: /app/vendor/acquia/blt/bin/blt
  xdebug-on:
    service: appserver
    description: Enable Xdebug.
    user: root
    cmd:
      - docker-php-ext-enable xdebug && kill -USR2 $(pgrep -o php-fpm) > /dev/null || /etc/init.d/apache2 reload
      - tput setaf 2 && echo "Xdebug On" && tput sgr 0 && echo
  xdebug-off:
    service: appserver
    description: Disable Xdebug.
    user: root
    cmd:
      - rm /usr/local/etc/php/conf.d/docker-php-ext-xdebug.ini && kill -USR2 $(pgrep -o php-fpm) > /dev/null || /etc/init.d/apache2 reload
      - tput setaf 1 && echo "Xdebug Off" && tput sgr 0 && echo
plugins:
  "@lando/mailhog": ../..
  "@lando/php": ../../node_modules/@lando/php
